version: "3.8"

services:
  app:
    container_name: ${APP_NAME}
    build: .
    restart: unless-stopped
    command: poetry run python main.py
    volumes:
      - .:/app
    environment:
      - DEBUG=0
