[project]
name = "python-project-template"
version = "0.1.0"
description = "A template python project"
requires-python = ">=3.10"

license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
authors = [{ name = "Diego Gamboa", email = "difegam3@gmail.com" }]

dependencies = ["requests>=2.32.3"]

[project.urls]
Repository = "https://github.com/difegam/python-project-template"

[project.scripts]
app = "python_project_template:main"
cli = "python_project_template.app:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "commitizen>=3.30.0",
    "pre-commit>=3.8.0",
    "pytest>=8.3.3",
    "ruff>=0.6.4",
    "docformatter>=1.7.5",
]

[tool.uv]
default-groups = ["dev"]

[tool.pytest.ini_options]
addopts = "-vvv"
testpaths = "tests"
pythonpath = "src"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "0.1.0"
version_scheme = "pep440"
version_provider = "pep621"
update_changelog_on_bump = true
