[tool.poetry]
name = "PROJECT-NAME"
version = "0.1.0"
description = "A template python project"
authors = ["difegam <difegam3@gmail.com>"]
readme = "README.md"

include = ["CHANGELOG.md", "LICENSE"]
license = "MIT"

keywords = [
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
PROJECT-NAME = "PROJECT-NAME.__main__:main"
